<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="234b2a92-c017-4844-8650-a78b7aaa2cc5" name="jfernandezt@JOSE-VAIO 2014-10-08 13:10:24" runUser="Jose-VAIO\jfernandezt" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="a02889c2-6b52-44bd-a167-3757354a0e9e">
    <Description>These are default test settings for a local test run.</Description>
    <Deployment enabled="false" runDeploymentRoot="jfernandezt_JOSE-VAIO 2014-10-08 13_10_24">
      <DeploymentItem filename="C:\Users\jfernandezt\Desktop\APP TEMPORAL\APP_RANSA_NET_COLAS\PY_RANSA_NET_WCF\PY_RANSA_NET_EN\bin\Debug\PY_RANSA_NET_EN.dll" />
    </Deployment>
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2014-10-08T13:10:24.0873178-05:00" queuing="2014-10-08T13:10:24.3813346-05:00" start="2014-10-08T13:10:24.4193368-05:00" finish="2014-10-08T13:10:28.8995930-05:00" />
  <ResultSummary outcome="Failed">
    <Counters total="2" executed="2" error="0" failed="2" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="RegistrarPedidoMovimiento" storage="c:\users\jfernandezt\desktop\app temporal\app_ransa_net_colas\py_ransa_net_wcf\py_ransa_net_ts\bin\debug\py_ransa_net_ts.dll" id="cd523e66-69fd-b81d-4747-76ad3e8197b0">
      <Execution id="ec8af905-9308-46a9-8504-7b4c21116f44" />
      <TestMethod codeBase="C:/Users/jfernandezt/Desktop/APP TEMPORAL/APP_RANSA_NET_COLAS/PY_RANSA_NET_WCF/PY_RANSA_NET_TS/bin/Debug/PY_RANSA_NET_TS.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="PY_RANSA_NET_TS.Cls_PedidoTS, PY_RANSA_NET_TS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="RegistrarPedidoMovimiento" />
    </UnitTest>
    <UnitTest name="ConsultaPedidoMovimiento" storage="c:\users\jfernandezt\desktop\app temporal\app_ransa_net_colas\py_ransa_net_wcf\py_ransa_net_ts\bin\debug\py_ransa_net_ts.dll" id="c18a5b4f-0de8-f588-f66f-1ed2055df807">
      <Execution id="29e67b18-f5ff-4369-9b42-93614522a775" />
      <TestMethod codeBase="C:/Users/jfernandezt/Desktop/APP TEMPORAL/APP_RANSA_NET_COLAS/PY_RANSA_NET_WCF/PY_RANSA_NET_TS/bin/Debug/PY_RANSA_NET_TS.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="PY_RANSA_NET_TS.Cls_PedidoTS, PY_RANSA_NET_TS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="ConsultaPedidoMovimiento" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="c18a5b4f-0de8-f588-f66f-1ed2055df807" executionId="29e67b18-f5ff-4369-9b42-93614522a775" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestEntry testId="cd523e66-69fd-b81d-4747-76ad3e8197b0" executionId="ec8af905-9308-46a9-8504-7b4c21116f44" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="29e67b18-f5ff-4369-9b42-93614522a775" testId="c18a5b4f-0de8-f588-f66f-1ed2055df807" testName="ConsultaPedidoMovimiento" computerName="JOSE-VAIO" duration="00:00:02.1250020" startTime="2014-10-08T13:10:24.4333376-05:00" endTime="2014-10-08T13:10:26.8174739-05:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="29e67b18-f5ff-4369-9b42-93614522a775">
      <Output>
        <ErrorInfo>
          <Message>Test method PY_RANSA_NET_TS.Cls_PedidoTS.ConsultaPedidoMovimiento threw exception: 
System.Net.WebException: No es posible conectar con el servidor remoto ---&gt; System.Net.Sockets.SocketException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión 127.0.0.1:2104</Message>
          <StackTrace>    en System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   en System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket&amp; socket, IPAddress&amp; address, ConnectSocketState state, IAsyncResult asyncResult, Exception&amp; exception)
 --- End of inner exception stack trace ---
    en System.Net.HttpWebRequest.GetResponse()
   en PY_RANSA_NET_TS.Cls_PedidoTS.ConsultaPedidoMovimiento() en C:\Users\jfernandezt\Desktop\APP TEMPORAL\APP_RANSA_NET_COLAS\PY_RANSA_NET_WCF\PY_RANSA_NET_TS\Cls_PedidoTS.cs:línea 65
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
    <UnitTestResult executionId="ec8af905-9308-46a9-8504-7b4c21116f44" testId="cd523e66-69fd-b81d-4747-76ad3e8197b0" testName="RegistrarPedidoMovimiento" computerName="JOSE-VAIO" duration="00:00:02.0051224" startTime="2014-10-08T13:10:26.8314747-05:00" endTime="2014-10-08T13:10:28.8405897-05:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="ec8af905-9308-46a9-8504-7b4c21116f44">
      <Output>
        <ErrorInfo>
          <Message>Test method PY_RANSA_NET_TS.Cls_PedidoTS.RegistrarPedidoMovimiento threw exception: 
System.Net.WebException: No es posible conectar con el servidor remoto ---&gt; System.Net.Sockets.SocketException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión 127.0.0.1:2104</Message>
          <StackTrace>    en System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   en System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket&amp; socket, IPAddress&amp; address, ConnectSocketState state, IAsyncResult asyncResult, Exception&amp; exception)
 --- End of inner exception stack trace ---
    en System.Net.HttpWebRequest.GetRequestStream(TransportContext&amp; context)
   en System.Net.HttpWebRequest.GetRequestStream()
   en PY_RANSA_NET_TS.Cls_PedidoTS.RegistrarPedidoMovimiento() en C:\Users\jfernandezt\Desktop\APP TEMPORAL\APP_RANSA_NET_COLAS\PY_RANSA_NET_WCF\PY_RANSA_NET_TS\Cls_PedidoTS.cs:línea 49
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
</TestRun>