<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="21f126f6-3c6d-41f9-920f-2a8371c1b2d2" name="jfernandezt@JOSE-VAIO 2014-10-08 21:22:44" runUser="Jose-VAIO\jfernandezt" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="a02889c2-6b52-44bd-a167-3757354a0e9e">
    <Description>These are default test settings for a local test run.</Description>
    <Deployment enabled="false" runDeploymentRoot="jfernandezt_JOSE-VAIO 2014-10-08 21_22_44">
      <DeploymentItem filename="D:\J - UPC\CICLO VI\SISTEMAS DISTRIBUIDOS\TRABAJO\APP\PY_RANSA_NET_MSG\PY_RANSA_NET_EN\bin\Debug\PY_RANSA_NET_EN.dll" />
    </Deployment>
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2014-10-08T21:22:44.6564702-05:00" queuing="2014-10-08T21:22:46.1035530-05:00" start="2014-10-08T21:22:46.2305603-05:00" finish="2014-10-08T21:22:46.7915924-05:00" />
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" error="0" failed="1" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="ConsultaPedidoMovimiento" storage="d:\j - upc\ciclo vi\sistemas distribuidos\trabajo\app\py_ransa_net_msg\py_ransa_net_ts\bin\debug\py_ransa_net_ts.dll" id="c18a5b4f-0de8-f588-f66f-1ed2055df807">
      <Execution id="82f12215-afb9-4e10-986c-ddc93e8459f9" />
      <TestMethod codeBase="D:/J - UPC/CICLO VI/SISTEMAS DISTRIBUIDOS/TRABAJO/APP/PY_RANSA_NET_MSG/PY_RANSA_NET_TS/bin/Debug/PY_RANSA_NET_TS.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="PY_RANSA_NET_TS.Cls_PedidoTS, PY_RANSA_NET_TS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="ConsultaPedidoMovimiento" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="c18a5b4f-0de8-f588-f66f-1ed2055df807" executionId="82f12215-afb9-4e10-986c-ddc93e8459f9" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="82f12215-afb9-4e10-986c-ddc93e8459f9" testId="c18a5b4f-0de8-f588-f66f-1ed2055df807" testName="ConsultaPedidoMovimiento" computerName="JOSE-VAIO" duration="00:00:00.1705760" startTime="2014-10-08T21:22:46.2755628-05:00" endTime="2014-10-08T21:22:46.7155880-05:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="82f12215-afb9-4e10-986c-ddc93e8459f9">
      <Output>
        <ErrorInfo>
          <Message>Test method PY_RANSA_NET_TS.Cls_PedidoTS.ConsultaPedidoMovimiento threw exception: 
System.Net.WebException: Error en el servidor remoto: (400) Solicitud incorrecta.</Message>
          <StackTrace>    en System.Net.HttpWebRequest.GetResponse()
   en PY_RANSA_NET_TS.Cls_PedidoTS.ConsultaPedidoMovimiento() en D:\J - UPC\CICLO VI\SISTEMAS DISTRIBUIDOS\TRABAJO\APP\PY_RANSA_NET_MSG\PY_RANSA_NET_TS\Cls_PedidoTS.cs:línea 66
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
</TestRun>